steps:
  # Step 1: Build with Maven
  - name: maven:3.8.4-openjdk-17
    entrypoint: mvn
    args: ['clean', 'package', '-DskipTests']
    id: Maven Build

  # Step 2: Build Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}', '.']
    id: Docker Build

  # Step 3: Push Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}']
    id: Push Image

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'payroll-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DBURL=${_DBURL},SECRETKEY=${_SECRETKEY},ALLOWEDURLS=${_ALLOWEDURLS}'
    id: Deploy

images:
  - 'gcr.io/$PROJECT_ID/$BRANCH_NAME:${_ENV}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _ENV: "dev"
  _SECRETKEY: "0qXaXU10h9wGE6TPGdRmUfA1DhuEKtoYnV4JyVc2i2Y="
  _DBURL: "mongodb+srv://manjudraj1971:Hrb81le02D4O2iUy@cluster1dev.q3d6h.mongodb.net/?retryWrites=true&w=majority"
  _ALLOWEDURLS: ""